package generator

import "github.com/ImSingee/god/utils"

var t = utils.GetTemplate("getter", `
// Code generated by god, DO NOT EDIT.

package {{ .pkg }}

{{ range $struct := .structs }}
{{ range $field := $struct.fields }}
func ({{ $struct.v }} *{{ $struct.name }}) {{ $field.public }}() {{ $field.type }} {
	return {{ .v }}.{{ $field.private }}
}
{{ end }}
{{ end }}
`)

func GenerateGetter() string {
	return ""
}
